// Generated by gencpp from file tele_operate/Control.msg
// DO NOT EDIT!


#ifndef TELE_OPERATE_MESSAGE_CONTROL_H
#define TELE_OPERATE_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tele_operate
{
template <class ContainerAllocator>
struct Control_
{
  typedef Control_<ContainerAllocator> Type;

  Control_()
    : control(0)  {
    }
  Control_(const ContainerAllocator& _alloc)
    : control(0)  {
  (void)_alloc;
    }



   typedef int64_t _control_type;
  _control_type control;





  typedef boost::shared_ptr< ::tele_operate::Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tele_operate::Control_<ContainerAllocator> const> ConstPtr;

}; // struct Control_

typedef ::tele_operate::Control_<std::allocator<void> > Control;

typedef boost::shared_ptr< ::tele_operate::Control > ControlPtr;
typedef boost::shared_ptr< ::tele_operate::Control const> ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tele_operate::Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tele_operate::Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tele_operate

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'tele_operate': ['/home/alistairfink/temp/temp2/WALL-ED/tele_operate/src/tele_operate/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tele_operate::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tele_operate::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tele_operate::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tele_operate::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tele_operate::Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tele_operate::Control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tele_operate::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69939a687db9b3fdb214ee8d790057ba";
  }

  static const char* value(const ::tele_operate::Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69939a687db9b3fdULL;
  static const uint64_t static_value2 = 0xb214ee8d790057baULL;
};

template<class ContainerAllocator>
struct DataType< ::tele_operate::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tele_operate/Control";
  }

  static const char* value(const ::tele_operate::Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tele_operate::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 control\n\
";
  }

  static const char* value(const ::tele_operate::Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tele_operate::Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tele_operate::Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tele_operate::Control_<ContainerAllocator>& v)
  {
    s << indent << "control: ";
    Printer<int64_t>::stream(s, indent + "  ", v.control);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TELE_OPERATE_MESSAGE_CONTROL_H
